project:
  type: book

book:
  chapters:
    - index.qmd
    - ack.qmd
    - abb.qmd
    - intro.qmd
    - lit_rev.qmd
    - potential2.qmd
    - empirical3.qmd
    - results2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    browser: brave
    theme: cosmo
    lot: true
    lof: true
    fontsize: 12pt
    linestretch: 1.5
    mermaid:
      theme: default
  pdf:
    documentclass: scrbook
    classoption:
      - oneside    # no blank pages between chapters
      - openany    # chapters start on any page, not forced to odd pages
    fontsize: 12pt
    linestretch: 1.5
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=3cm
      - right=2.5cm
    loc: true
    lot: false
    lof: false
    number-sections: true
    include-in-header:
      text: |
        \usepackage{pdfpages}
    include-before-body:
      text: |
        \includepdf[pages=1-2, fitpaper=true]{outside_inside_cover.pdf}
        \frontmatter

    
execute:
  echo: false
  warning: false
  





