# Abstract {.unnumbered}

In this dissertation we investigate the patterns of technological diversification in European regions. Specifically we inquire on the factors that contribute to the feasibility of a diversification option. Our focus in this work is to provide a context rich assessment that bridge different gaps in the literature namely relatedness, network positions, institutions, and the role of space. To operationalise this contextualised assessment we first address methodological and conceptual issues in the relatedness constructs. 

Our methodological alternative is a machine learning training strategy that shift relatedness from a descriptive exercise to a predictive exercise Our alternative approach enables us to construct a bidirectional network that's inherently more granular and informative than conventional technology space approaches. Similarly, our approach also enables us to quantify the feasibility of a specific technology for each region, we call this quantity regional technological potential. 

With these two constructs, we divide technologies into two categories based on their role in the network structure, bridging technologies and enabling technologies. Then we investigate which technologies are more feasible, and whether the industrial alignment between the region's portfolio of technologies and a target technology moderate that relationship. Additionally, we incorporate national ecosystem co-variates that describe institutional and market conditions into our analysis to investigate their contribution in the feasibility of a diversification option. Lastly, we investigate whether or not these dynamics are space dependent and whether this dependency is stable at different effect channels. 

Our results shows four main conclusions. First, we validate that our regional technological potential is an adequate predictor of entry to new technologies. Second we confirm that different network structures are strong predictor or technological potential. Third industrial alignment is our strongest predictor here and moderates the relationship between network structures and potential. Forth, we show that national entrepreneurial ecosystem characteristics are substantial predictors of regional technological potential and that their effect is stable but heterogeneous for different pillars. Fifth, and lastly, we confirm the spatial dependency at the regional portfolio level, and show that the average characteristics of these portfolios in terms of their endowment of bridging and enabling technologies are similarly strong and consistent predictors of aggregate regional potential and that industrial alignment remains a substantial moderation mechanism that's stable across all effect channels.  