# Acknowledgement {.unnumbered}


*I dedicate this work to my parents. Thank you for raising me right. Thank you for being patient with me. Thank you for always being on my side. To my partner and best friend, without you by my side, this wouldn't have been possible, thank you.*

To my Supervisors, thank you for the support, the encouragement, the guidance, and for believing in me. I'm immensely grateful, without your commitment and engagement this wouldn't have seen the light. Thank you for challenging me, for making me a better person, and a better researcher.

I'm equally grateful for the faculty, teachers and staff whose support was essential and who made -- through their kind words and acts -- even the darkest days shine bright. 


I'm thankful for my friend who paved the way for me to get here. And to my colleagues, who made my journey full of memories I will forever cherish. 

*To my past self who was full of doubt, this is a testament of your hard work and dedication. The result of your struggles, discipline, and perseverance . Always move forward, that's the only way, everything else is temporary.*